### ISSUE TITLE
Please upload utils folder

### ISSUE THREAD

**Issue by zchengxiu** [miacsu/MTTU-Net#3]
I can't import all_reduce_tensor from utils.tools ，please upload utils folder. thanks.

**Comment by nengwp** [comment]
https://github.com/Wenxuan-1119/TransBTS/tree/main/utils

**Comment by HYY0508** [comment]
In /classification/SENet, senet3d34()=senet3d50()?,I can't understand, is it wrong that both are the same?

**Comment by NadiyaC249** [comment]
I can't import all_reduce_tensor from utils.tools ，please upload utils folder. thanks.

**Comment by chengjianhong** [comment]
@zchengxiu @nengwp @NadiYa924 @HYY0508 Hi all. The file has been updated. Thank you for your attention.
